# Generated by Django 4.0.4 on 2022-05-15 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agd', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='food_type',
            field=models.CharField(default='food', max_length=10),
        ),
    ]
