# Generated by Django 4.0.4 on 2022-05-15 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agd', '0006_order_ordered_foods_alter_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='food_type',
            field=models.CharField(default=['drink', 'food', 'dessert'], max_length=10),
        ),
    ]
