# Generated by Django 4.0.4 on 2022-05-15 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agd', '0007_alter_food_food_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='ordered_foods',
        ),
    ]
