# Generated by Django 4.0.4 on 2022-05-15 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agd', '0008_remove_order_ordered_foods'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ordered_foods',
            field=models.ManyToManyField(through='agd.OrderedFoods', to='agd.food'),
        ),
    ]
